test

diff --git a/Jenkins b/Jenkins
--- a/Jenkins
+++ b/Jenkins
@@ -1,17 +1,35 @@
-pipieline
+pipeline
 {
-    agent 
-    {
-        dockerfile true
-    }
+    agent dockerfile true
     stages
     {
-        stage('Test docker')
+        stage('Build and send initial slack message')
         {
-            steps 
+            steps
             {
-                echo 'Hello World'
+                sh 'echo Building...'
+                slackSend message:"Build Started - ${env.JOB_NAME}"
             }
         }
+        stage('Linting') {
+            steps {
+                script {
+                    docker.image('hadolint/hadolint:latest-debian').inside() {
+                            sh 'hadolint ./Dockerfile | tee -a hadolint_lint.txt'
+                            sh '''
+                                lintErrors=$(stat --printf="%s"  hadolint_lint.txt)
+                                if [ "$lintErrors" -gt "0" ]; then
+                                    echo "Errors have been found, please see below"
+                                    cat hadolint_lint.txt
+                                    exit 1
+                                else
+                                    echo "There are no erros found on Dockerfile!!"
+                                fi
+                            '''
+                    }
+                }
+            }
+        }
+        
     }
 }
