checking docker on Jenkins

diff --git a/Jenkins b/Jenkins
--- a/Jenkins
+++ b/Jenkins
@@ -11,20 +11,21 @@ pipeline
                 slackSend message:"Build Started - ${env.JOB_NAME}"
             }
         }
-        stage('set up')
-        {
-            agent
-            {
-                dockerfile true
-            }
-        
-            steps
-            {
-                script
-                {
-                    docker.image('python:3.7.3-stretch').inside()
-                    {
-                        sh "make setup install lint"
+        stage('Lint Dockerfile') {
+            steps {
+                script {
+                    docker.image('hadolint/hadolint:latest-debian').inside() {
+                            sh 'hadolint ./Dockerfile | tee -a hadolint_lint.txt'
+                            sh '''
+                                lintErrors=$(stat --printf="%s"  hadolint_lint.txt)
+                                if [ "$lintErrors" -gt "0" ]; then
+                                    echo "Errors have been found, please see below"
+                                    cat hadolint_lint.txt
+                                    exit 1
+                                else
+                                    echo "There are no erros found on Dockerfile!!"
+                                fi
+                            '''
                     }
                 }
             }
